# Generated by Django 4.2.6 on 2023-10-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_stud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stud',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
